# Jekyll settings file for blog.xiaket.org
title: 年华转瞬
email: kaix@fastmail.com
description: 夏恺, xiaket, 读书人, Pythonista, DevOps
url: "https://xiaket.github.io"
twitter_username: xiaket
github_username:  xiaket
permalink: /:year/:title:output_ext
timezone: Australia/Melbourne

# Build settings
markdown: kramdown
kramdown:
  # I hate that ID.
  auto_ids: false

# minima is just a placeholder here. We are not using it.
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude: ["Gemfile", "Gemfile.lock", "manage", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]

collections:
  novels:
    output: true
    permalink: /novels/:path/

defaults:
  -
    values:
      layout: "post"
      lang: "lang-zh-hans"
  -
    scope:
      path: "_novels"
    values:
      layout: "chapter"
      lang: "lang-zh-hans"

m17n:
  en:
    desc:  "Bookworm/Pythonista/DevOps/Melburnian"
  zh:
    desc:  "读书人/Pythonista/DevOps/居墨尔本"
